### PR TITLE
Fix nonzero validator to not validate nil array or slices.

### LINKED ISSUE #147: Prevent validation on custom structs for nil values
According to https://github.com/elastic/go-ucfg/blob/master/validator.go#L213, the validation tag `nonzero` should only return an error if the configuration value is present but zero. 
For custom types this is not always the case at the moment.

Eg. have following custom type and configuration raises an error even if the `hosts` field is not present:
```
type urls []*url.URL

type MyConfig struct {
  Hosts urls `config:"hosts" validate:"nonzero"`
}
```

### PR DESCRIPTION
**Pull request by blakerouse**
Fixes issue where the `nonzero` validator would fail when the array or slice was `nil` value.

This also includes fixes for map types where nonzero or required would not validate them correctly.

Closes elastic/go-ucfg#147

### CODE REVIEW

File: validator.go [hunk 1]
```diff
@@ -414,7 +418,10 @@ func validateNonEmpty(v interface{}, _ string) error {
 	}
 
 	val := reflect.ValueOf(v)
-	if val.Kind() == reflect.Array || val.Kind() == reflect.Slice {
+	if val.Kind() == reflect.Array || val.Kind() == reflect.Slice || val.Kind() == reflect.Map {
+		if allowNil && val.IsNil() {
+			return nil
+		}
```
Comment (urso) [inline validator.go]: we might want to return `ErrMissing` instead of `ErrEmpty` if we have a `nil` value.

Comment (blakerouse) [reply validator.go]: I think it would be weird to return an error that doesn't match the validator type. `nonzero` case is always a `ErrEmpty` everywhere else and required is always `ErrRequired`.

Comment (urso) [reply validator.go]: I see `validateRequired` will replace the error value to always return `ErrRequired`.

Still the error string is also for the user. Maybe `validateRequired` should still return `ErrEmpty` if the setting is in the config, but does not contain any entry.

Comment (blakerouse) [reply validator.go]: I recently change validateRequired to do that, a few PR's ago. I assumed that was the behaviour that was expected.

It was surprising to me that the code path returned `ErrEmpty` when the `required` tag was used. But if its more about what is show to the user and less about the developer handling those errors, then I should switch it back.

Comment (urso) [reply validator.go]: I see. The error type and message should reflect the actual problem that has been found, not the validator that failed. The `required` validator can fail for 2 reasons: a) field was not configured at all b) field was configured, but object or array was empty itself. Failure (a) warrants ErrRequired, while failure (b) should trigger an ErrEmpty error. That is the original `ErrEmpty` for the `required` check was on purpose, not by accident.

ErrRequired is somewhat similar to ErrMissing. The error message says `"missing required field"`. If the array is in the config file but empty the error message should say `"empty field"`. We might even opt to introduce more specific errors like ErrEmptyArray, or ErrEmptyMap, or ErrValueIsZero. WDYT?

Comment (blakerouse) [reply validator.go]: Yeah I think it would be better to have more detailed errors messages like the `ErrEmptyArray` and the `ErrEmptyMap`. I will work on returning those errors in the correct locations.

**Comment by blakerouse** [comment]
@urso This is ready for another review.

File: validator.go [hunk 2]
```diff
@@ -418,12 +418,21 @@ func validateNonEmptyWithAllowNil(v interface{}, _ string, allowNil bool) error
 	}
 
 	val := reflect.ValueOf(v)
-	if val.Kind() == reflect.Array || val.Kind() == reflect.Slice || val.Kind() == reflect.Map {
+	if val.Kind() == reflect.Array || val.Kind() == reflect.Slice {
 		if allowNil && val.IsNil() {
 			return nil
 		}
```
Comment (urso) [inline validator.go]: how about:

```
if v.IsNil() {
  if allowNil {
    return nil
  }
  return ErrRequired
}
```

Comment (blakerouse) [reply validator.go]: Works for me. Done!

File: validator_test.go [hunk 3]
```diff
@@ -552,24 +559,24 @@ func TestValidateRequiredFailing(t *testing.T) {
 		{ErrRequired, &struct {
 			A int `validate:"required"`
 		}{}},
-		{ErrRequired, &struct {
+		{ErrEmpty, &struct {
```
Comment (urso) [inline validator_test.go]: oh, string is special. Just like for `int` I would expect an `ErrRequired` here.

File: validator_test.go [hunk 4]
```diff
@@ -552,24 +559,24 @@ func TestValidateRequiredFailing(t *testing.T) {
...
 			A string `validate:"required"`
 		}{}},
-		{ErrRequired, &struct {
+		{ErrArrayEmpty, &struct {
```
Comment (urso) [inline validator_test.go]: `A` should be nil. Would expect an `ErrRequired`, no?

File: validator_test.go [hunk 5]
```diff
@@ -580,20 +587,39 @@ func TestValidateRequiredFailing(t *testing.T) {
 		{ErrRequired, &struct {
 			C int `validate:"required"`
 		}{}},
-		{ErrRequired, &struct {
+		{ErrEmpty, &struct {
```
Comment (urso) [inline validator_test.go]: I think this one is debatable. `C` is on the config, but nil. Both `ErrEmpty` and `ErrRequired` might make sense (just in case some other change modifies this error value).

**Comment by robgil** [comment]
# [Codecov](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=h1) Report
> Merging [#148](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=desc) into [master](https://codecov.io/gh/elastic/go-ucfg/commit/093a6898c440d2e5e93abf09850068c60428b2cd&el=desc) will **decrease** coverage by `0.34%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #148      +/-   ##
==========================================
- Coverage   78.37%   78.02%   -0.35%     
==========================================
  Files          24       24              
  Lines        2714     2730      +16     
==========================================
+ Hits         2127     2130       +3     
- Misses        431      444      +13     
  Partials      156      156              
```


| [Impacted Files](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [merge.go](https://codecov.io/gh/elastic/go-ucfg/pull/148/diff?src=pr&el=tree#diff-bWVyZ2UuZ28=) | `80.00% <0.00%> (-2.15%)` | :arrow_down: |
| [types.go](https://codecov.io/gh/elastic/go-ucfg/pull/148/diff?src=pr&el=tree#diff-dHlwZXMuZ28=) | `73.31% <0.00%> (-0.93%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=footer). Last update [093a689...5cd3649](https://codecov.io/gh/elastic/go-ucfg/pull/148?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
